version: '3'
services:
  kru-docker:
    image: ghcr.io/jannik-schroeder/kru-docker:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kru-docker-secure.rule=Host(`deine-domain.de`)"
      - "traefik.http.routers.kru-docker-secure.entrypoints=websecure"
      - "traefik.http.routers.kru-docker-secure.tls=true"

# Traefik reverse proxy (recommended)
# ---
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
# (Optional) Enable cloudflare ACME challenge
#    environment:
#      - CF_API_EMAIL=cloudfalre-email
#      - CF_API_KEY=globale-api-key
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true) - traefik/traefik.yaml here
    volumes:
      - ./traefik:/etc/traefik
      - /var/log/traefik:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
# Nginx reverse proxy (alternative to traefik)
# ---
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /var/log/nginx:/var/log/nginx
#      - ./certs/example.crt:/etc/ssl/certs/example.crt:ro
#      - ./certs/example.key:/etc/ssl/private/example.key:ro
